# Generated by Django 4.2.2 on 2023-06-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado_pedido',
            options={'verbose_name': 'Estado de pedido'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name': 'Medios de pago'},
        ),
    ]
