# Generated by Django 4.2.2 on 2023-06-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo', '0002_alter_estado_pedido_options_alter_metodopago_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresas',
            options={'verbose_name': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Productos'},
        ),
    ]
