# Generated by Django 4.2.2 on 2023-06-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo', '0003_alter_empresas_options_alter_productos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresas',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='estado_pedido',
            options={'verbose_name': 'Estado de pedido', 'verbose_name_plural': 'Estado de pedidos'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name': 'Medio de pago', 'verbose_name_plural': 'Medios de pago'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
