# Generated by Django 4.2.2 on 2023-07-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo', '0003_alter_direcciones_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalles_pedido',
            options={'verbose_name': 'Detalle de pedido', 'verbose_name_plural': 'Detalle de pedidos'},
        ),
        migrations.AddField(
            model_name='pedidos',
            name='instrucciones_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nombre_empresa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='urlfoto',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
