# Generated by Django 4.2.2 on 2023-06-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo', '0004_alter_empresas_options_alter_estado_pedido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
