# Generated by Django 4.2.2 on 2023-06-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo', '0005_alter_pedidos_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='run',
            new_name='rut',
        ),
        migrations.AlterField(
            model_name='detalles_pedido',
            name='idPedidos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telovendo.pedidos'),
        ),
        migrations.AlterField(
            model_name='detalles_pedido',
            name='idProductos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telovendo.productos'),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telovendo.empresas'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='idEmpresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='telovendo.empresas'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='idEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telovendo.estado_pedido'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='idMetodoPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telovendo.metodopago'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='idUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='telovendo.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='idEmpresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='telovendo.empresas'),
        ),
    ]
