# Generated by Django 4.2.2 on 2023-07-04 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo', '0006_alter_pedidos_total_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_pedido',
            name='idPedidos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telovendo.pedidos'),
        ),
    ]
