# Generated by Django 4.2.2 on 2023-07-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo', '0007_alter_detalles_pedido_idpedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('permiso_clientes', 'Permisos necesarios para clientes'), ('permiso_trabajadores', 'Permisos necesarios para trabajadores')),
            },
        ),
    ]
