# Generated by Django 4.2.2 on 2023-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo', '0008_secciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Categoría del Pedido',
                'verbose_name_plural': 'Categorías del Pedido',
            },
        ),
        migrations.RemoveField(
            model_name='productos',
            name='urlfoto',
        ),
        migrations.AddField(
            model_name='productos',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='product_images'),
        ),
    ]
