# Generated by Django 4.2.2 on 2023-07-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo', '0009_categoria_remove_productos_urlfoto_productos_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría del Producto', 'verbose_name_plural': 'Categorías de Productos'},
        ),
    ]
